### ISSUE TITLE
Invalid Network Interface name

### ISSUE THREAD

**Issue by akashva22** [Gurpreet06/Wifi-Crack#4]
**OS: MAC Catalina┃**
![Screenshot 2022-08-28 at 2 27 55 PM](https://user-images.githubusercontent.com/35763811/187066188-653b3da5-9cf6-41a8-8eec-bb554209e804.png)

  [!] Invalid Network Interface name
ls: /sys/class/net: No such file or directory
Traceback (most recent call last):
  File "wifiCrack.py", line 742, in <module>
    check_parms()
  File "wifiCrack.py", line 702, in check_parms
    get_inters = subprocess.check_output("ls /sys/class/net", shell=True).decode().strip()
  File "/Users/aku/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/aku/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ls /sys/class/net' returned non-zero exit status 1.

**Comment by akashva22** [comment]
Command used:
" sudo python3 wifiCrack.py -i en0 -m Handshake "
en0 being default wi-fi network interface name.

**Comment by Gurpreet06** [comment]
Currently the script is only compatible with Linux systems, that's why you get the error. If you test it on a Linux system it will work fine and in "README.md" I have mentioned the operating systems on which the script has been tested.

![image](https://user-images.githubusercontent.com/74554439/187072861-7ad7f653-29ec-4a81-a706-149eeb3ea796.png)

**Comment by Hiro231** [comment]
Bro,make a video for that code how run everything in kali Linux that code

**Comment by Gurpreet06** [comment]
To use the script run the following commands in the Kali Linux ---> **sudo python3 wifiCrack.py  -i YOUR-WIFI-INTERFACE -m ATTACK-NAME**.
